Hackeando a urna eletrônica
kuca-belludo/urnas pull request #5
Opened 2022-12-30 01:19 UTC by Matheus-P

Eternizando um momento único na história da internet brasileira cf. https://twitter.com/brasilpodcastbr/status/1608175851765383168?t=t32F3rdJGkqfR4nppeYUSg&s=19

2022-12-30 02:09 UTC, MarcusGoldschmidt approved these changes

2022-12-30 02:11 UTC, OProfeta requested changes
Pegou do StackOverFlow, não pode plágio. Dá processo.

2022-12-30 02:16 UTC, abraaowendel approved these changes
PARABÉNS!

2022-12-30 10:25 UTC, WicCaesar approved these changes

2022-12-30 12:08 UTC, GabrielLasso commented
O https://github.com/kuca-belludo/urnas/pull/6 tá mais completo, pode fechar esse aqui

2022-12-30 12:41 UTC, Matheus-P commented
> O #6 tá mais completo, pode fechar esse aqui

Mas o if da linha 34 sem o Than vai dar erro de sintaxe, infelizmente o vídeo não permite que vejamos a contribuição completa do hacker

2022-12-30 13:36 UTC, GabrielLasso commented
> > O #6 tá mais completo, pode fechar esse aqui
> 
> Mas o if da linha 34 sem o Than vai dar erro de sintaxe, infelizmente o vídeo não permite que vejamos a contribuição completa do hacker

E o if sem () e o Than 13 do nada não dá nada né? Kkkkk

2022-12-30 18:56 UTC, maxmiliano approved these changes
LGTM!

2023-01-01 20:03 UTC, yDanonin approved these changes
LGTM! 🚀

2023-02-05 20:16 UTC, closed without merging